// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Product struct {
	ID        int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
	Sku       string
	Name      string
	Price     pgtype.Numeric
	Quantity  int32
}

type ProductPromotion struct {
	ID            int32
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
	PromotionID   int32
	ProductID     int32
	MinQuantity   int32
	FreeProductID *int32
	Discount      pgtype.Numeric
	FreeQuantity  *int32
	PayY          *int32
}

type Promotion struct {
	ID            int32
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
	PromotionType string
	StartDate     pgtype.Timestamptz
	EndDate       pgtype.Timestamptz
}
